#!/usr/bin/expect -f
set timeout 10

spawn scp -o StrictHostKeyChecking=no scratch/seed_db.js root@95.111.226.90:/var/www/nazorat-backend/seed_db.js
expect {
    "password:" {
        send "Bahodir2009\r"
        expect eof
    }
    eof {
    }
}

spawn ssh -o StrictHostKeyChecking=no root@95.111.226.90 "cd /var/www/nazorat-backend && node seed_db.js && rm seed_db.js"
expect {
    "password:" {
        send "Bahodir2009\r"
        expect eof
    }
    eof {
    }
}
